// default yaml configuration for starship pipeline and associated view config

---
# Starship Pipeline Configuration
pipeline:
  id: starship/demo@0.0.1
  steps:

    - tool: starship/random-question
      description: AI generates a random question about LLMs.
      input: { }
      saveAs: question

    - tool: starship/execute-view
      description: Using semantic text similarity models, we look for matching paragraphs in a set of source documents.
      input:
        input: { "$var": "question" }
      saveAs: viewResult

    - tool: prompt/text-summarize/simplify-audience
      description: The answer is summarized for the target audience.
      input:
        input: { "$var": "viewResult" }
        audience: (UI option)
      saveAs: simpleResponse

    - tool: prompt/docs-reduce/outline
      description: The answer can be transformed in other ways depending on the use case.
      input:
        input: { "$var": "viewResult" }
      saveAs: outline

    - tool: prompt/docs-reduce/technical-terms
      input:
        input: { "$var": "viewResult" }
      saveAs: technicalTerms

    - tool: prompt/text-translate/translate
      input:
        input: { "$var": "viewResult" }
        instruct: (UI option, random language)
      saveAs: translatedResponse

# Starship Widget Layout Configuration
layout:
  backgroundIcon: STAR_ALT
  backgroundIconCount: 1000

  numCols: 3
  numRows: 3
  isShowGrid: true

  widgets:
    - varName: question
      widgetType: ANIMATING_TEXT
      pos: { x: 1, y: 1, width: 1, height: 2 }
      overlay:
        step: 1
        title: Question
        icon: QUESTION
        iconSize: 48
        explain: AI generates a random question.

    - varName: starship/execute-view
      widgetType: ANIMATING_TEXT
      pos: { x: 1, y: 3, width: 2, height: 1 }
      overlay:
        step: 2
        explain: Using semantic text similarity models, we look for matching paragraphs in a set of source documents.

    - varName: starship/answer-question
      widgetType: ANIMATING_TEXT
      pos: { x: 1, y: 2, width: 1, height: 1 }
      overlay:
        step: 3
        title: Answer
        icon: FILE_PDF_ALT
        iconSize: 24
        explain: LLMs answer the question using the matching paragraphs.

    - varName: prompt/text-summarize/simplify-audience
      widgetType: ANIMATING_TEXT
      pos: { x: 2, y: 2, width: 1, height: 1 }
      overlay:
        step: 4
        title: Summarize For
        icon: COMMENTS
        iconSize: 24
        explain: The answer is summarized for the target audience.
        options:
          audience: [ "a general audience", "elementary school students", "high school students", "software engineers", "executives" ]

    - varName: prompt/docs-reduce/outline
      widgetType: ANIMATING_TEXT_VERTICAL
      pos: { x: 3, y: 1, width: 1, height: 3 }
      overlay:
        step: 5
        iconSize: 16
        explain: The answer can be transformed in other ways depending on the use case.

    - varName: prompt/docs-reduce/technical-terms
      widgetType: ANIMATING_TEXT_VERTICAL
      # use same coordinate and height=0 to stack vertically
      pos: { x: 3, y: 1, width: 1, height: 0 }

    - varName: prompt/text-translate/translate
      widgetType: ANIMATING_TEXT_VERTICAL
      overlay:
        options:
          instruct: [ "a random language", "English", "Spanish", "French", "German", "Chinese", "Japanese", "Emoji", "Korean", "Russian", "Arabic", "Hindi", "Portuguese", "Italian" ]
      # use same coordinate and height=0 to stack vertically
      pos: { x: 3, y: 1, width: 1, height: 0 }
