---
groupId: generate-config
defaults: { category: configuration }
prompts:

  - id: generate-config/promptfx-view-config@1.0.0
    title: Generate View Config
    description: Generates a structured view configuration YAML block based on a description of the desired capability.
    template: |
      You are a system configuration assistant. Given the following description, generate a prompt and a YAML view configuration compatible with the existing system.
  
      Description:
      '''
      {{{input}}}
      '''
      
      The result schema should match the following example:
      ```yaml
      date-extraction:
        category: Text
        title: Date Extraction
        description: Extract all dates from input text and provide as a list.
        modeOptions:
          - templateId: DATE_FORMAT
            label: Date Format
            values:
              - ISO8601 Date
              - MMM dd, yyyy
              - the 12th of February
        promptConfig:
          id: date-extraction # require unique ID for the prompt
          template-prompt: | # jinja template for the prompt
            Extract a list of dates from the following text, and format as {{DATE_FORMAT}}:
            '''
            {{info}}
            '''
        isShowModelParameters: false
        isShowMultipleResponseOption: false
      ```
  
      Requirements:
      - Use proper YAML syntax.
      - Use snake_case for the view ID.
      - Include 'category', 'title', 'description'.
      - Use 'modeOptions' if helpful for guided user customization beyond the input. Otherwise, leave as an empty list.
      - Use 'promptConfig' with a unique ID and 'template-prompt' field for the Jinja template prompt.
        - Always include an 'input' template placeholder.
        - Include placeholders for all specified mode options, with ids matching precise templateId values (including case).
      - Set isShowModelParameters and isShowMultipleResponseOption to false unless otherwise implied.
  
      Output: