# Library of view configurations
---
date-extraction:
  category: Text
  title: Date Extraction
  description: Extract all dates from input text and provide as a list.
  modeOptions:
    - id: date-formats
      templateId: DATE_FORMAT
      label: Date Format
  promptConfig:
    id: date-extraction
  isShowModelParameters: false
  isShowMultipleResponseOption: false

entity-extraction:
  category: Text
  title: Entity Extraction
  description: Extract entities from text (runtime override)
  modeOptions:
    - id: entities
      templateId: mode
      label: Mode
    - id: structured-format
      templateId: format
      label: Format as
  promptConfig:
    id: entity-extraction
  isShowModelParameters: true