# Library of view configurations
---
rag_qa_prefilter_json:
  category: RAG QA
  title: Prefilter JSON Generation
  description: Generate JSON to prefilter large document sets based on user queries.
  modeOptions: []
  promptConfig:
    id: rag_qa_prefilter_json
    template-prompt: |
      Given the user's query, extract relevant information to prefilter a large document set. Create a JSON object using filter fields such as:
        - Date/Time Range
        - Sources
        - Language
        - Perspective
        - Geographic Area of Interest (AOI)
        - etc.
      Only include a field if the user has provided information for it. If the user has not provided information for a field, do not include it in the JSON object.
      
      User query:
      {{{
      input
      }}}
      
      Today is {{today}}.

      Sample Output:
      {
        "datetime": {
          "start": "2010-01-01",
          "stop": "2010-12-31",
        },
        "sources": [ "CNN", "Wikipedia" ],
        "aoi": "Europe"
      }
  isShowModelParameters: false
  isShowMultipleResponseOption: false

math_unit_conversion:
  category: Math
  title: Unit Conversions
  description: Convert units to a specified unit
  modeOptions:
    - templateId: UNIT_TYPE
      label: Unit Type
      values:
        - Length
        - Mass
        - Volume
    - templateId: CONVERT_TO_UNIT
      label: Convert To Unit
      values:
        - Meter
        - Kilogram
        - Liter
  promptConfig:
    id: math_unit_conversion
    template-prompt: |
      Enter the value to convert and the unit type to convert from, and specify the unit to convert to:
      '''
      Value: {{ input }}
      Convert from: {{ UNIT_TYPE }}
      Convert to: {{ CONVERT_TO_UNIT }}
      '''
  isShowModelParameters: false
  isShowMultipleResponseOption: false

math_calculations:
  category: Math
  title: Math Calculations
  description: Perform various math calculations efficiently.
  promptConfig:
    id: math-calculations
    template-prompt: |
      Perform math calculations on the following numbers:
      '''
      {{input}}
      '''
  modeOptions:
    - templateId: OPERATION_TYPE
      label: Operation Type
      values:
        - Addition
        - Subtraction
        - Multiplication
        - Division
  isShowModelParameters: false
  isShowMultipleResponseOption: false

date-extraction:
  category: Text
  title: Date Extraction
  description: Extract all dates from input text and provide as a list.
  promptConfig:
    id: date-extraction
  modeOptions:
    - templateId: DATE_FORMAT
      label: Date Format
      values:
        - ISO8601 Date
        - MMM dd, yyyy
        - yyyy/MM/dd
        - the 12th of February
  isShowModelParameters: false
  isShowMultipleResponseOption: false

entity-extraction:
  category: Text
  title: Entity Extraction
  description: Extract entities from text (testing runtime override)
  promptConfig:
    id: entity-extraction
  modeOptions:
    - id: entities
      templateId: mode
      label: Mode
    - id: structured-format
      templateId: format
      label: Format as
  isShowModelParameters: true