# Library of view configurations
---
code-review:
  category: Code
  prompt:
    id: code/code-review@1.0.0
    name: code-review
    title: Request Code Review
    description: Asks the LLM to analyze provided code and suggest improvements or bug fixes
    arguments:
      - name: code
        description: The code to review
        required: true
  template-prompt: |
    Please review the following code and provide suggestions for improvements or bug fixes:
    ```
    {{{code}}}
    ```